# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: projectronin.fhir
canonical: http://projectronin.com/fhir/us/ronin
name: RoninOncologyFHIRProfile
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Project Ronin Inc.
  url: https://www.projectronin.com
  email: contact@projectronin.com
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: The Ronin oncology FHIR profile assembles a core set of structured data elements 
  for oncology based on FHIR 4.0.1 and mCODE™ standards.
# For now the license is set to not-open-source - legal needs to evaluate what's appropriate
# FHIR 4.0.1 licenses http://hl7.org/fhir/R4/valueset-spdx-license.html
license: not-open-source
dependencies:
  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.mcode: 1.16.0 
parameters:
  show-inherited-invariants: true
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
