#actions
name: Compile and deploy Ronin FHIR implementation guide

on:
  push:
    branches: [DP-693]

jobs:
  update_dp_ronin_profile_pages:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2.1.0
        - uses: benjlevesque/short-sha@v1.2
          id: short-sha
          with:
            length: 8
        - name: Copy guide to dp-ronin-fhir-profile-page
          uses: webfactory/ssh-agent@v0.5.1
          with:
            ssh-private-key: ${{ secrets.DP_RONIN_FHIR_PROFILE_PAGES_PRIV_KEY }}
        - run: |
            cd ..
            git clone git@github.com:projectronin/dp-ronin-fhir-profile-pages.git
            git config --global user.email "data-platform@projectronin.com"
            git config --global user.name "data platform auto user"
            rm -rf dp-ronin-fhir-profile-pages/docs
            mkdir -p dp-ronin-fhir-profile/output
            echo "TEST" >> dp-ronin-fhir-profile/output/file.html
            cp -rp dp-ronin-fhir-profile/output dp-ronin-fhir-profile-pages/docs
            cd dp-ronin-fhir-profile-pages
            git add docs
            git commit -m "refreshing dp Ronin FHIR profile docs ${{ steps.short-sha.outputs.sha }}"
            git push